Repository esastack/esa-restlight, pull requests merged in 2021-12, with the labels that each got.

#88 remove xxxTrailer apis in HttpRequest and HttpResponse
  restlight-core/src/main/java/io/esastack/restlight/core/context/impl/HttpResponseAdapter.java
  restlight-server-adapter/src/main/java/io/esastack/httpserver/core/HttpRequest.java
  restlight-server-adapter/src/main/java/io/esastack/httpserver/core/HttpResponse.java
  restlight-server-adapter/src/main/java/io/esastack/httpserver/impl/HttResponseImpl.java
  restlight-server-adapter/src/test/java/io/esastack/httpserver/impl/HttpRequestImplTest.java
  restlight-server-adapter/src/test/java/io/esastack/httpserver/impl/HttpResponseImplTest.java
  restlight-test/restlight-test-mock/src/main/java/io/esastack/restlight/test/mock/MockHttpResponse.java
  restlight-test/restlight-test-mock/src/test/java/io/esastack/restlight/test/mock/MockHttpResponseTest.java
Labels: refactor

#91 fix the bug related to filter in MockMvc
  restlight-ext/restlight-ext-filter-starter/src/main/java/io/esastack/restlight/ext/filter/starter/autoconfigurer/RestlightExtFilterAutoConfiguration.java
  restlight-server/src/main/java/io/esastack/restlight/server/BaseDeployments.java
  restlight-server/src/main/java/io/esastack/restlight/server/BaseRestlightServer.java
  restlight-spring/src/main/java/io/esastack/restlight/spring/AbstractRestlight4Spring.java
  restlight-starter-actuator/src/main/java/io/esastack/restlight/starter/actuator/ConfigurableManagementRestlight.java
  restlight-starter-actuator/src/test/java/io/esastack/restlight/starter/actuator/ConfigurableManagementRestlightTest.java
  restlight-starter/src/main/java/io/esastack/restlight/starter/ConfigurableRestlight.java
  restlight-starter/src/main/java/io/esastack/restlight/starter/autoconfigure/RestlightServerAutoConfigurer.java
  restlight-starter/src/test/java/io/esastack/restlight/starter/ConfigurableRestlightTest.java
  restlight-test/restlight-test-starter/src/main/java/io/esastack/restlight/test/autoconfig/AutoMockMvcOptions.java
  restlight-test/restlight-test-starter/src/main/java/io/esastack/restlight/test/autoconfig/MockMvcAutoConfiguration.java
  restlight-test/restlight-test-starter/src/main/java/io/esastack/restlight/test/bootstrap/Deployments4SpringMvcTest.java
  restlight-test/restlight-test-starter/src/main/java/io/esastack/restlight/test/bootstrap/Deployments4SpringTest.java
  restlight-test/restlight-test-starter/src/main/java/io/esastack/restlight/test/bootstrap/FakeServer.java
  restlight-test/restlight-test-starter/src/main/java/io/esastack/restlight/test/bootstrap/FullyMockMvcBuilder.java
  restlight-test/restlight-test-starter/src/main/java/io/esastack/restlight/test/bootstrap/Restlight4SpringMvcTest.java
  restlight-test/restlight-test-starter/src/main/java/io/esastack/restlight/test/bootstrap/Restlight4SpringTest.java
  restlight-test/restlight-test-starter/src/main/java/io/esastack/restlight/test/condition/ConditionalOnMockMvc.java
  restlight-test/restlight-test-starter/src/main/java/io/esastack/restlight/test/condition/EnableMockCondition.java
  restlight-test/restlight-test-starter/src/main/java/io/esastack/restlight/test/conflict/ConflictResolverAutoConfiguration.java
  restlight-test/restlight-test-starter/src/test/java/io/esastack/restlight/test/bootstrap/FakeServerTest.java
Labels: bug

#94 stop logging bizExceptions which will be handled by ExceptionHandler
  restlight-core/src/main/java/io/esastack/restlight/core/handler/impl/AbstractExecutionHandler.java
  restlight-server/src/main/java/io/esastack/restlight/server/bootstrap/DispatcherHandlerImpl.java
Labels: discussion

#95 replace HttpResponseStatus with HttpStatus
  restlight-core/src/main/java/io/esastack/restlight/core/handler/HandlerMethodInfo.java
  restlight-core/src/main/java/io/esastack/restlight/core/handler/RouteMethodInfo.java
  restlight-core/src/main/java/io/esastack/restlight/core/handler/impl/AbstractExecutionHandler.java
  restlight-core/src/main/java/io/esastack/restlight/core/handler/impl/HandlerMethodResolver.java
  restlight-core/src/main/java/io/esastack/restlight/core/handler/locate/AbstractRouteMethodLocator.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/reqentity/FlexibleRequestEntityResolverFactory.java
  restlight-ext/restlight-ext-filter/src/main/java/io/esastack/restlight/ext/filter/cors/CorsFilter.java
  restlight-ext/restlight-ext-filter/src/main/java/io/esastack/restlight/ext/filter/ipwhitelist/IpWhiteListFilter.java
  restlight-ext/restlight-ext-filter/src/test/java/io/esastack/restlight/ext/filter/cors/CorsFilterTest.java
  restlight-ext/restlight-ext-interceptor/src/main/java/io/esastack/restlight/ext/interceptor/signature/AbstractSignatureInterceptor.java
  restlight-ext/restlight-ext-validator/src/main/java/io/esastack/restlight/ext/validator/ValidationExceptionHandlerFactory.java
  restlight-jaxrs-provider/src/main/java/io/esastack/restlight/jaxrs/impl/core/RequestImpl.java
  restlight-jaxrs-provider/src/main/java/io/esastack/restlight/jaxrs/impl/core/ResponseImpl.java
  restlight-jaxrs-provider/src/main/java/io/esastack/restlight/jaxrs/spi/JaxrsRouteMethodLocatorFactory.java
  restlight-server-adapter/src/main/java/io/esastack/httpserver/core/HttpResponse.java
  restlight-server/src/main/java/io/esastack/restlight/server/bootstrap/DispatcherHandlerImpl.java
  restlight-server/src/main/java/io/esastack/restlight/server/bootstrap/WebServerException.java
  restlight-server/src/main/java/io/esastack/restlight/server/schedule/ScheduledHandler.java
  restlight-server/src/main/java/io/esastack/restlight/server/schedule/TimeoutScheduler.java
  restlight-server/src/main/java/io/esastack/restlight/server/spi/impl/RouteFailureExceptionHandler.java
  restlight-server/src/main/java/io/esastack/restlight/server/util/ErrorDetail.java
  restlight-springmvc-provider/src/main/java/io/esastack/restlight/springmvc/spi/SpringMvcRouteMethodLocatorFactory.java
  restlight-springmvc-provider/src/main/java/io/esastack/restlight/springmvc/spi/core/SpringMvcExceptionHandlerFactory.java
  restlight-springmvc-provider/src/main/java/io/esastack/restlight/springmvc/util/ResponseStatusUtils.java
Labels: refactor

#100 fix the bugs related to NameAndVakue
  restlight-common/src/main/java/io/esastack/restlight/core/util/ConverterUtils.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/nav/NameAndStringValueResolver.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/nav/NameAndValue.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/nav/NameAndValueResolverAdapter.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/param/AbstractParamResolver.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/param/QueryBeanParamResolver.java
  restlight-core/src/main/java/io/esastack/restlight/core/spi/impl/DefaultStringConverterFactory.java
  restlight-ext/restlight-ext-multipart/src/main/java/io/esastack/restlight/ext/multipart/spi/MultipartFileParamResolver.java
Labels: fix
