Repository esastack/esa-restlight, pull requests merged in 2022-04, with the labels that each got.

#134 introduce Result that represents either success [Ok] or failure [Err])
  pom.xml
  restlight-core/src/main/java/io/esastack/restlight/core/AbstractRestlight.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/HandledValue.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/RequestEntityResolver.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/RequestEntityResolverContextImpl.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/ResponseEntityResolver.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/ResponseEntityResolverContextImpl.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/reqentity/FixedRequestEntityResolverFactory.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/reqentity/FlexibleRequestEntityResolverFactory.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/rspentity/AbstractResponseEntityResolver.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/rspentity/FixedResponseEntityResolver.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/rspentity/FlexibleResponseEntityResolver.java
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/rspentity/ResponseFileEntityResolver.java
  restlight-core/src/main/java/io/esastack/restlight/core/serialize/BaseHttpBodySerializer.java
  restlight-core/src/main/java/io/esastack/restlight/core/serialize/HttpRequestSerializer.java
  restlight-core/src/main/java/io/esastack/restlight/core/serialize/HttpResponseSerializer.java
  restlight-core/src/main/java/io/esastack/restlight/core/serialize/Serializers.java
  restlight-jaxrs-provider/src/main/java/io/esastack/restlight/jaxrs/adapter/MessageBodyReaderAdapter.java
  restlight-jaxrs-provider/src/main/java/io/esastack/restlight/jaxrs/adapter/MessageBodyWriterAdapter.java
  restlight-jaxrs-provider/src/test/java/io/esastack/restlight/jaxrs/adapter/MessageBodyReaderAdapterTest.java
  restlight-jaxrs-provider/src/test/java/io/esastack/restlight/jaxrs/adapter/MessageBodyWriterAdapterTest.java
  restlight-jaxrs-provider/src/test/java/io/esastack/restlight/jaxrs/resolver/reqentity/FixedRequestEntityResolverFactoryImplTest.java
  restlight-jaxrs-provider/src/test/java/io/esastack/restlight/jaxrs/resolver/reqentity/FlexibleRequestEntityResolverFactoryImplTest.java
  restlight-springmvc-provider/src/test/java/io/esastack/restlight/springmvc/resolver/reqentity/FixedRequestEntityResolverFactoryImplTest.java
  restlight-springmvc-provider/src/test/java/io/esastack/restlight/springmvc/resolver/reqentity/FlexibleRequestEntityResolverFactoryImplTest.java
  restlight-test/restlight-test-starter/src/test/java/io/esastack/restlight/test/bootstrap/MinorityMockMvcBuilderTest.java
Labels: refactor

#151 fix bug with null context when extracting ExceptionHandler(#147)
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/exception/AbstractExceptionResolverFactory.java
  restlight-springmvc-provider/src/main/java/io/esastack/restlight/springmvc/resolver/exception/SpringMvcExceptionResolverFactory.java
Labels: bug

#156 fix bug without suitable resolver to handle param(#137)
  restlight-core/src/main/java/io/esastack/restlight/core/Deployments.java
  restlight-starter-actuator/src/main/java/io/esastack/restlight/starter/actuator/adapt/BaseHandlerMappingProvider.java
  restlight-starter-actuator/src/main/java/io/esastack/restlight/starter/actuator/adapt/EndpointHandlerMethod.java
  restlight-starter-actuator/src/main/java/io/esastack/restlight/starter/actuator/adapt/JaxrsHandlerMappingProvider.java
  restlight-starter-actuator/src/main/java/io/esastack/restlight/starter/actuator/adapt/SpringMvcHandlerMappingProvider.java
  restlight-starter-actuator/src/main/java/io/esastack/restlight/starter/actuator/endpoint/RestlightBizThreadPoolEndpoint.java
  restlight-starter-actuator/src/main/java/io/esastack/restlight/starter/actuator/endpoint/RestlightConfigEndpoint.java
  restlight-starter-actuator/src/main/java/io/esastack/restlight/starter/actuator/endpoint/RestlightIoExecutorEndpoint.java
  restlight-starter-actuator/src/test/java/io/esastack/restlight/starter/actuator/adapt/EndpointHandlerMethodTest.java
  restlight-starter-actuator/src/test/java/io/esastack/restlight/starter/actuator/adapt/JaxrsHandlerMappingProviderTest.java
  site/content/en/docs/actuator_support/restlight_endpoints.md
Labels: fix

#159 fix bug parsing error when requestBody is byte[](#139)
  restlight-core/src/main/java/io/esastack/restlight/core/resolver/reqentity/FlexibleRequestEntityResolverFactory.java
Labels: fix

#160 fix bug that JacksonSerializer's date format pattern is not yyyy-MM-d…(#140)
  restlight-starter/src/main/java/io/esastack/restlight/starter/autoconfigure/JacksonAutoConfiguration.java
Labels: fix

#161 fix bug that NPE will be thrown when use pojo as the RequestParam.(#141)
  restlight-core/src/main/java/io/esastack/restlight/core/spi/impl/DefaultStringConverterFactory.java
Labels: fix
